import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Plugins',
      link: {
        type: 'doc',
        id: 'plugins/index',
      },
      items: [{ type: 'autogenerated', dirName: 'plugins' }],
    },
  ],
};

export default sidebars;