import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Sidebar generated for this site:
 * - Intro
 * - Plugins (autogenerated from docs/plugins)
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Plugins',
      items: [{ type: 'autogenerated', dirName: 'plugins' }],
    },
  ],
};

export default sidebars;
